#!/bin/bash
if [ "$JDBC_DRIVER" == "" ]
then
JDBC_DRIVER=/usr/share/java/postgresql-jdbc4.jar
#echo "JDBC_DRIVER environment variable not set. Assumed path: $JDBC_DRIVER"
fi
if [ "$GIGI_EXEC" == "" ]
then
GIGI_EXEC=/usr/share/java/gigi.jar
#echo "GIGI_EXEC environment variable not set. Assumed path: $GIGI_EXEC" 
fi

cd /var/lib/cacert-gigi

if [ "$1" == "start" ]
then
	java -cp $JDBC_DRIVER:$GIGI_EXEC org.cacert.gigi.Launcher
elif [ "$1" == "debug" ]
then
	java -cp $JDBC_DRIVER:$GIGI_EXEC -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000 org.cacert.gigi.Launcher
elif [ "$1" == "start-daemon" ]
then
	if [ ! -e /etc/cacert/gigi/conf.tar ]; then
		echo "Config missing."
		exit 1;
	fi
	java -cp $JDBC_DRIVER:$GIGI_EXEC org.cacert.gigi.Launcher < /etc/cacert/gigi/conf.tar >> /var/log/cacert-gigi.log 2>&1 &
	echo $! > /var/run/cacert-gigi.pid
elif [ "$1" == "signer" ]
then
	java -cp $JDBC_DRIVER:$GIGI_EXEC org.cacert.gigi.util.SimpleSigner
elif [ "$1" == "reset-database" ]
then
	java -cp $JDBC_DRIVER:$GIGI_EXEC org.cacert.gigi.util.DatabaseManager
elif [ "$1" == "fetch-locales" ]
then
    if [ "$2" == "" ]; then
		java -cp $JDBC_DRIVER:$GIGI_EXEC org.cacert.gigi.util.FetchLocales
	else
		java -cp $JDBC_DRIVER:$GIGI_EXEC org.cacert.gigi.util.FetchLocales "$2"
	fi
elif [ "$1" == "signer-conf" ]
then
	mkdir /var/lib/cacert-gigi/config
	cd /var/lib/cacert-gigi/config
	tar x gigi.properties
else
	echo "Usage: gigi <option>"
	echo "debug - starts gigi in debug mode (on port 8000, with config from stdin)"
	echo "fetch-locales - (re)fetch the localisation"
	echo "reset-database - resets the database"
	echo "signer - starts the simple signer"
	echo "signer-conf - extract config for simple signer (and reset-database) from the tar from stdin"
	echo "start - starts gigi"
	echo "start-daemon - starts gigi in background (using config from /etc/cacert/gigi/conf.tar)"

fi
